version: "3.9"
services:
  server:
    image: httpd:2.4-alpine
    restart: always
    volumes:
      - ./data:/var/spool/apt-mirror
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
  client:
    build: .
    volumes:
      - ./data:/var/spool/apt-mirror
      - ./mirror.list:/etc/apt/mirror.list
    profiles:
      - update
